### ISSUE TITLE
iOS Pod install 失败

### ISSUE THREAD

**Issue by qq432591** [rongcloud/rongcloud-rtc-flutter-sdk#12]
为了快速解决问题，在寻求帮助的时候，请提供以下信息，方便我们快速定位问题
* 本地 Flutter 版本信息
* 异常设备是 iOS 还是 Android，列出具体机型和系统
* 所调用的是什么 API 或者说是什么功能
* 完整的报错信息或者问题描述
* 提供问题发生时必要的日志，并以 txt 形式上传

报错信息如下：

➜ pod install
Analyzing dependencies
[!] Failed to load 'rongcloud_rtc_plugin' podspec:
[!] Invalid `rongcloud_rtc_plugin.podspec` file: No such file or directory @ rb_sysopen - /Users/jiandan/Desktop/version.config.

    from /Users/jiandan/Desktop/AppProject/ios/.symlinks/plugins/rongcloud_rtc_plugin/ios/rongcloud_rtc_plugin.podspec:7
    -------------------------------------------
  
 >  File.foreach(config) do |line|
        # matches = line.match(/rongcloud_rtc_plugin_version\=(.*)/)
    -------------------------------------------

**Comment by GP-Moon** [comment]
需要在example/ios目录下执行pod install

**Comment by qq432591** [comment]
@GP-Moon 
这个是我在pub.dev上检索到rongcloud_rtc_plugin: ^4.0.4 这个，然后集成到项目当中，
执行flutter pub get 的时候回报错，提示执行pod install。
在iOS 的工程目录下执行的时候 pod install 的时候就会出现该问题。

**Comment by GP-Moon** [comment]
@qq432591 你好，针对这个问题我们刚刚更新了一个小版本，4.0.4+1

**Comment by qq432591** [comment]
@GP-Moon 
刚试了一下 pod install 报错如下：
- Running pre install hooks
    [!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (/Users/jiandan/Desktop/AppProject/ios/Pods/Libyuv/lib/libyuv.a,
    /Users/jiandan/Desktop/AppProject/ios/Pods/RongCloudIM/RongCloudIM/libopencore-amrnb.a,
    /Users/jiandan/Desktop/AppProject/ios/Pods/RongCloudIM/RongCloudIM/libopencore-amrwb.a,
    /Users/jiandan/Desktop/AppProject/ios/Pods/RongCloudIM/RongCloudIM/libvo-amrwbenc.a,
    /Users/jiandan/Desktop/AppProject/ios/Pods/RongCloudIM/RongCloudIM/RongIMLib.framework, and
    /Users/jiandan/Desktop/AppProject/ios/Pods/RongRTCLib/RTCLib/RongRTCLib.framework)

    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/target_validator.rb:84:in `block (2 levels) in
    verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/target_validator.rb:74:in `each_key'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/target_validator.rb:74:in `block in verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/target_validator.rb:73:in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/target_validator.rb:73:in `verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/target_validator.rb:38:in `validate!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:590:in `validate_targets'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:158:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

**Comment by qq432591** [comment]
刚工单解决了，
在rongcloud_rtc_plugin.podspec里添加这个 
s.static_framework = true
