### ISSUE TITLE
会议模式闪退！

### ISSUE THREAD

**Issue by qq432591** [rongcloud/rongcloud-rtc-flutter-sdk#14]
为了快速解决问题，在寻求帮助的时候，请提供以下信息，方便我们快速定位问题
* 本地 Flutter 版本信息
* 异常设备是 iOS 还是 Android，列出具体机型和系统
* 所调用的是什么 API 或者说是什么功能
* 完整的报错信息或者问题描述
* 提供问题发生时必要的日志，并以 txt 形式上传

当前版本4.0.4+2
iOS设备，
会议模式下，用户A创建并加入房间后，用户B加入该房间的话会闪退！

flutter: joinRoom json: {data: {id: 665522, localUser: {id: 93}, remoteUserList: [{id: 5, streamList: [{mute: false, state: true, streamId: 5_RongCloudRTC, type: 0, tag: RongCloudRTC, userId: 5}, {mute: false, state: true, streamId: 5_RongCloudRTC, type: 1, tag: RongCloudRTC, userId: 5}]}]}, code: 0}
[log] D/rcrtc@RCRTCLocalUser: subscribeStreams [{"streamId":"5_RongCloudRTC","tag":"RongCloudRTC","type":0},{"streamId":"5_RongCloudRTC","tag":"RongCloudRTC","type":1}]
Lost connection to device.
Exited (sigterm)

**Comment by GP-Moon** [comment]
4.0.4+3版本已修复。
