### ISSUE TITLE
AS无法运行的

### ISSUE THREAD

**Issue by zhanchi88** [rongcloud/rongcloud-rtc-flutter-sdk#2]
为了快速解决问题，在寻求帮助的时候，请提供以下信息，方便我们快速定位问题
* 本地 Flutter 版本信息
* 异常设备是 iOS 还是 Android，列出具体机型和系统
* 所调用的是什么 API 或者说是什么功能
* 完整的报错信息或者问题描述
* 提供问题发生时必要的日志，并以 txt 形式上传

**Comment by loginSin** [comment]
你是如何运行该项目的，可以按照下面的方式处理一下
1.终端进入该项目的根路径，执行 `flutter pub get` 来更新 Flutter 依赖的各种 SDK
2.进入 `example` 目录执行 `flutter run` 命令安装运行 apk ，如果是 android9 及其以上的手机可能无法将 apk 安装到手机，此时可以按照第三步做
3.使用 Android studio 打开 `example/android` 目录，然后使用 Android studio 直接运行即可

**Comment by zhanchi88** [comment]
我是Android studio打开项目。先在主yaml里点击packages get然后进入example点击packages get然后点击运行。
华为nove2s HWI-TL00 android 9
