### ISSUE TITLE
Android studio运行demo出错

### ISSUE THREAD

**Issue by zhanchi88** [rongcloud/rongcloud-rtc-flutter-sdk#3]
为了快速解决问题，在寻求帮助的时候，请提供以下信息，方便我们快速定位问题
* 本地 Flutter 版本:1.12.13+hotfix.5
* 异常设备 Android,HUAWEI HWI-TL00. anroid 9  运行demo
* 问题描述：
1.终端进入该项目的根路径，执行 flutter pub get 来更新 Flutter 依赖的各种 SDK
2.使用 Android studio 打开 example/android 目录，然后使用 Android studio 直接运行即可
按照以上步骤打开demo运行出错
* 日志：

12/25 10:41:25: Launching 'app' on HUAWEI HWI-TL00.
$ adb shell am start -n "cn.rongcloud.rongcloud_rtc_plugin_example/cn.rongcloud.rongcloud_rtc_plugin_example.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Error while executing: am start -n "cn.rongcloud.rongcloud_rtc_plugin_example/cn.rongcloud.rongcloud_rtc_plugin_example.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=cn.rongcloud.rongcloud_rtc_plugin_example/.MainActivity }
Error type 3
Error: Activity class {cn.rongcloud.rongcloud_rtc_plugin_example/cn.rongcloud.rongcloud_rtc_plugin_example.MainActivity} does not exist.

Error while Launching activity

**Comment by loginSin** [comment]
1.终端进入该项目的根路径，执行 flutter pub get 来更新 Flutter 依赖的各种 SDK
2.终端运行 flutter run 命令将 dart 生成对应的 .so 文件，如果是 Android 9 以下设备可以正常安装 apk，如果是 Android 9 以上设备可能会卡在安装 apk 的过程，此时中断  flutter run 命令执行第 3 步
3.使用 Android studio 打开 example/android 目录，然后使用 Android studio 直接运行即可

简单来说大致三部
1.更新 Flutter SDK
2.将 Flutter SDK 生成对应的 so 文件，供 Android 使用（这个是为什么 Flutter 能够跨平台的原因）
3.用 Android studio 打开对应的 example/android 目录，即可当成一个正常的 Android 工程使用
